[metadata] 
name = audiossl
author = lixian 
email = shysian@gmail.com
version = 0.1 
[options] 
install_requires = 
    absl-py
    audioread
    dcase_util
    einops
    fairseq
    librosa
    lmdb
    matplotlib
    mkl-fft
    mkl-random
    mkl-service
    pandas
    psds_eval
    pyarrow
    pytorch-lightning
    scipy
    sed_eval
    tensorboard
    torchaudio
    torchvision
    tqdm
    wandb
    protobuf
    typeguard
    easydict
    nnAudio
    torchmetrics
