python -m audiossl.methods.atstframe.downstream.train_as_strong \
--nproc 0, \
--learning_rate 1e-2 \
--arch frameatst \
--pretrained_ckpt_path "/workspace/models/atst_ft_StrongAS_eps28.ckpt" \
--dcase_conf "/workspace/audiossl/methods/atstframe/downstream/utils_as_strong/conf/frame_6.yaml" \
--dataset_name as_strong \
--save_path "./logs/as_strong_small/" \
--batch_size_per_gpu 2 \
--num_workers 2 \
--prefix "_small_freeze" \
--max_epochs 30 \
--warmup_epochs 1 \
--freeze_mode
